### ISSUE TITLE
Dependency/python-bidi: removed  Removed algorithm.py from python-bidi package

### ISSUE THREAD

**Issue by kiran1415** [xhtml2pdf/xhtml2pdf#770] opened 2024-07-23 15:03 UTC
### Describe the Bug

removed the algorithm.py from python-bidi module and we have import at xhtml2pdf/util.py line 25
so we need to replace the 
`from bidi.algorithm import get_display
` with
`from bidi import get_display
`

XHTML2PDF version:v0.2.16
python-bidi Version: 0.5.0

**Comment by stefan6419846** [comment] 2024-07-23 15:26
Duplicate of #766.

**Closed** 2024-07-24 15:10 UTC
Labels: bug
