### ISSUE TITLE
Add support for `border-radius` CSS property

### ISSUE THREAD

**Issue by pedro-jmanuel** [xhtml2pdf/xhtml2pdf#617] opened 2022-06-01 15:18 UTC
I'm trying to draw a circle but it doesn't work

.badge {
            height: 100px;
            width: 100px;
            display: table-cell;
            text-align: center;
            vertical-align: middle;
            border-radius: 50%; /* may require vendor prefixes */
            background: yellow;
        }

**Comment by vivekdotbaruah** [comment] 2022-06-21 07:14
@pedro-jmanuel Here is a list of CSS properties supported by **xhtml2pdf** [link](https://xhtml2pdf.readthedocs.io/en/latest/reference.html#supported-css-properties)

**Comment by timoludwig** [comment] 2023-02-02 17:58
Duplicate of #542

**Closed by timoludwig** 2023-02-02 17:58 UTC
Labels: feature request, CSS

**Comment by crhea93** [comment] 2024-01-24 19:37
Hi,
 I've run into the same issue. This is a very basic feature that should be added. Not having this option is very prohibitive.
