### ISSUE TITLE
Footer not displayed in 0.2.8 and 0.2.7

### ISSUE THREAD

**Issue by sblondon** [xhtml2pdf/xhtml2pdf#653] opened 2022-11-29 17:08 UTC
The footer frame is not displayed in pdf file when following the documentation.

How to reproduce:
- create a virtualenv with xhtml2pdf library:

```
python3 -m venv venv
./venv/bin/pip install xhtml2pdf
```

- add an `index.html` file containing the example at https://xhtml2pdf.readthedocs.io/en/latest/format_html.html#example-with-2-static-frames-and-1-content-frame
 - `./venv/bin/xhtml2pdf index.html`

The generated `index.pdf` shows only 'Lyrics-R-Us' and 'To PDF or not to PDF'.

It could occurs in others releases. I only checked these two releases.

**Comment by tomasrpita** [comment] 2022-11-30 15:36
I have the same problem, I went from 0.2.5 to 0.28 and the footers stopped being generated.

**Comment by filipsworks** [comment] 2022-12-09 06:25
Have the same issue with images near the bottom of the page being bottom-cropped with percentage depending of their height. Issue is present since 0.2.6. Had to pin back 0.2.5 (and reportlab to 3.6.6)

**Comment by timoludwig** [comment] 2023-02-01 14:29
Is this a duplicate of #644? If so, can it be closed since #628 has been merged?

**Comment by timoludwig** [comment] 2023-02-02 14:12
Duplicate of #644 and #564

**Closed by timoludwig** 2023-02-02 14:12 UTC
Labels: bug, regression

**Comment by sblondon** [comment] 2023-02-02 17:54
I confirm the test case is fixed in 0.2.9.
