### ISSUE TITLE
Using `<pdf:pagenumber>` outside `footer_content` prints 0

### ISSUE THREAD

**Issue by pesikj** [xhtml2pdf/xhtml2pdf#546] opened 2021-02-07 22:15 UTC
I want to use the `pdf:pagecount` tag in a normal text, i.e. outside the footer. When I use the `footer_content` class for the `div` element with the `pdf:pagecount` tag, the page number and page count is properly generated.

```
    <div id="footer_content">Page <pdf:pagenumber> of <pdf:pagecount>
    </div>

```
However, when I do not use the `footer_content` class, the `pdf:pagenumber` tag prints 0 for all pages and the tag `pdf:pagecount` does not print anything at all.

```
    <div>Page <pdf:pagenumber>
        of <pdf:pagecount>
    </div>
```

Is there some solution how to use the `pdf:pagecount` tag outside the `footer_content` class?

**Comment by timoludwig** [comment] 2023-02-02 00:43
Duplicate of #322

**Closed by timoludwig** 2023-02-02 00:43 UTC
Labels: tags, bug
