### ISSUE TITLE
`<pdf:pagenumber>` displayed as 0

### ISSUE THREAD

**Issue by sergosamkharadze** [xhtml2pdf/xhtml2pdf#654] opened 2022-12-05 15:07 UTC
I have noticed that pagenumber and pagecount does not render on html

**Comment by timoludwig** [comment] 2023-02-01 14:27
Can you provide more insight how to reproduce this problem?

**Comment by timoludwig** [comment] 2023-02-01 22:28
Ah, you're probably using `<pdf:pagenumber>` outside of `footer_content`, right? Then, this is a duplicate of #546.

**Closed by timoludwig** 2023-02-01 22:28 UTC
Labels: needs-reproduction-info, tags, bug
