### ISSUE TITLE
Footer content is not displayed 0.2.8

### ISSUE THREAD

**Issue by zhusihan-python** [xhtml2pdf/xhtml2pdf#644] opened 2022-11-02 13:20 UTC
i found this [issue](https://github.com/xhtml2pdf/xhtml2pdf/issues/564) have been fixed before, yet i got empty footer content with 0.2.8 on windows 10 python 3.10.8
other dependencies:
PyPDF3-1.0.6 arabic-reshaper-2.1.4 asn1crypto-1.5.1 certifi-2022.9.24 charset-normalizer-2.1.1 click-8.1.3 cryptography-38.0.1 cssselect2-0.7.0 future-0.18.2 html5lib-1.1 idna-3.4 lxml-4.9.1 oscrypto-1.3.0 pyHanko-0.15.1 pyhanko-certvalidator-0.19.6 python-bidi-0.4.2 pytz-2022.5 pytz-deprecation-shim-0.1.0.post0 pyyaml-6.0 requests-2.28.1 six-1.16.0 svglib-1.4.1 tinycss2-1.2.1 tqdm-4.64.1 tzdata-2022.5 tzlocal-4.2 uritools-4.0.0 urllib3-1.26.12 webencodings-0.5.1 xhtml2pdf-0.2.8
demo code from [documentation](https://xhtml2pdf.readthedocs.io/en/latest/format_html.html#example-with-2-static-frames-and-1-content-frame)
```
<html>
<head>
<style>
    @page {
        size: a4 portrait;
        @frame header_frame {           /* Static Frame */
            -pdf-frame-content: header_content;
            left: 50pt; width: 512pt; top: 50pt; height: 40pt;
        }
        @frame content_frame {          /* Content Frame */
            left: 50pt; width: 512pt; top: 90pt; height: 632pt;
        }
        @frame footer_frame {           /* Another static Frame */
            -pdf-frame-content: footer_content;
            left: 50pt; width: 512pt; top: 772pt; height: 20pt;
        }
    }
</style>
</head>

<body>
    <!-- Content for Static Frame 'header_frame' -->
    <div id="header_content">Lyrics-R-Us</div>

    <!-- Content for Static Frame 'footer_frame' -->
    <div id="footer_content">(c) - page <pdf:pagenumber>
        of <pdf:pagecount>
    </div>

    <!-- HTML Content -->
    To PDF or not to PDF
</body>
</html>
```

**Comment by zhusihan-python** [comment] 2022-11-02 13:27
put a `<div>footer</div>` in footer_content can be shown, it seems `<pdf:pagenumber>` did not work inside footer_content
![image](https://user-images.githubusercontent.com/23504604/199501497-4e096502-8085-4c67-aaa4-c4aacb978f91.png)

**Comment by zhusihan-python** [comment] 2022-11-02 14:06
install from lastest master branch will not get blank footer
`python setup.py install`
![image](https://user-images.githubusercontent.com/23504604/199509391-c8e6224f-6470-4640-80cd-d46d2dd4e422.png)
but the pagecount is wrong, a 3 pages pdf got 33 pagecount
![image](https://user-images.githubusercontent.com/23504604/199510302-93ea6a4d-a602-4e69-9325-ade854044136.png)

**Comment by zhusihan-python** [comment] 2022-11-07 08:55
i found out a solution that get right page count:
if the footer_content div tag is in the same line, the pagecount is duplicated, 1 is 11, 3 is 33
        `<div id="footer_content"><pdf:pagenumber>/<pdf:pagecount></div>`
put them in two line, everything works fine
```
        <div id="footer_content"><pdf:pagenumber>/<pdf:pagecount>
        </div>
```
quite weird behaviour,
and the package in pypi need to be updated btw.

**Comment by jorenham** [comment] 2022-11-11 10:01
possible duplicate of https://github.com/xhtml2pdf/xhtml2pdf/issues/618 and https://github.com/xhtml2pdf/xhtml2pdf/issues/564

**Comment by d3viliz3d** [comment] 2023-01-24 09:27
> possible duplicate of #618 and #564 should have been fixed in #628

I have the same exact issue on 0.2.8... Looks like it wasn't fixed somehow.

**Comment by timoludwig** [comment] 2023-02-01 14:27
Since #628 was merged and a new version is released now, can we close this issue?

**Comment by timoludwig** [comment] 2023-02-02 14:13
Duplicate of #564

**Closed by timoludwig** 2023-02-02 14:13 UTC
Labels: duplicate
