### ISSUE TITLE
Using `<pdf:pagenumber>` outside `footer_content` prints 0

### ISSUE THREAD

**Issue by bukovyn** [xhtml2pdf/xhtml2pdf#389] opened 2018-03-19 19:37 UTC
Running into some trouble where `<pdf:pagenumber>` is working as intended in the footer div, but when trying to display page number as `<div> Page <pdf:pagenumber> of <pdf:pagecount> </div>`,  `<pdf:pagecount>` returns null and the html displays `Page X of  ' '`.

**Comment by timoludwig** [comment] 2023-02-02 01:14
Duplicate of #322

**Closed by timoludwig** 2023-02-02 01:14 UTC
