### ISSUE TITLE
TOC not working

### ISSUE THREAD

**Issue by jr2578s** [xhtml2pdf/xhtml2pdf#463] opened 2020-01-09 16:19 UTC
using Python 3.7.3 and reportlab 3.5.
if i add TOC  <pdf:toc /> to my template following error occurs:

> File "C:\development\projects\amdreport\venv\lib\site-packages\xhtml2pdf\reportlab_paragraph.py", line 1553, in drawPara
    if f.underline or f.link or f.strike:
AttributeError: 'ParaFrag' object has no attribute 'underline'

same goes for the strike attribute. Deleting both in the if statement shows a toc, but i dont know which effects it has and if it works like it should now.
Also the TOC doesnt show headings if they are in tables, which i did for formatting, but well i could change that.

**Comment by witefab** [comment] 2020-01-10 08:41
I have the same issue.

**Comment by thmo** [comment] 2020-01-27 17:06
Duplicate of #404.

**Comment by fbernhart** [comment] 2020-10-08 11:29
Seems like this has been solved by PR #486, just like #404 . So with the next release of xhtml2pdf, it should work without problems.

The following is running without errors, while using the current master branch, Python 3.9 and reportlab 3.5.53:
```
<html>
<head>
<style>

pdftoc {
    color: #666;
}
pdftoc.pdftoclevel0 {
    font-weight: bold;
    margin-top: 0.5em;
}
pdftoc.pdftoclevel1 {
    margin-left: 1em;
}
pdftoc.pdftoclevel2 {
    margin-left: 2em;
    font-style: italic;
}
</style>
</head>
<body>

<h1>Heading 1</h1>
<p>Some Text...</p>
<br>
<h1>Heading 2</h1>
<p>Some Text...</p>
<br>
<h1>Heading 3</h1>
<h2>Subheading 1</h2>
<p>Some Text...</p>
<br>
<h1>Heading 4</h1>
<h2>Subheading 2</h2>
<p>Some Text...</p>
<h2>Subheading 3</h2>
<p>Some Text...</p>
<br>
<br>
<br>
<pdf:toc />

</body>
</html>
```

Result:

[Test.pdf](https://github.com/xhtml2pdf/xhtml2pdf/files/5347490/Test.pdf)

**Comment by Swendude** [comment] 2020-10-08 13:12
That is great news as I just encountered this. Is there any work around until this is released?

**Comment by fbernhart** [comment] 2020-10-08 13:17
@Swendude 

You can simply use pip to install the master branch of xhtml2pdf on GitHub instead the default version on PyPI.

**Comment by luisza** [comment] 2020-10-08 19:00
Hi, this was solved in 0.2.5  release, now available on pypi.

**Closed by luisza** 2020-10-08 19:00 UTC

**Comment by akshathakl14** [comment] 2026-01-30 05:59
Hi @fbernhart ,

https://github.com/xhtml2pdf/xhtml2pdf/issues/463#issuecomment-705508262
I have used <pdf:toc /> as shown in above comment but my application gets crashed. Which version of xhtml2pdf supports this <pdf:toc />? How can the crash issue be resolved?

Versions Used :
Python Version : 3.13.0 
xhtml2pdf Version : 0.2.17

**Comment by fbernhart** [comment] 2026-01-30 23:06
> Hi [@fbernhart](https://github.com/fbernhart) ,
> 
> [#463 (comment)](https://github.com/xhtml2pdf/xhtml2pdf/issues/463#issuecomment-705508262) I have used <pdf:toc /> as shown in above comment but my application gets crashed. Which version of xhtml2pdf supports this <pdf:toc />? How can the crash issue be resolved?
> 
> Versions Used : Python Version : 3.13.0 xhtml2pdf Version : 0.2.17


Hi @akshathakl14,

I haven't worked with xhtml2pdf in years, but out of curiosity I've just installed it again and I could still recreate my example file from 2020.


I've used xhtml2pdf 0.2.17 and Python 3.14.2.

Seems like something in your code is wrong. Can you show the error message you're getting?

My code used:
```
from xhtml2pdf import pisa

html_source = """
<html>
<head>
<style>

pdftoc {
    color: #666;
}
pdftoc.pdftoclevel0 {
    font-weight: bold;
    margin-top: 0.5em;
}
pdftoc.pdftoclevel1 {
    margin-left: 1em;
}
pdftoc.pdftoclevel2 {
    margin-left: 2em;
    font-style: italic;
}
</style>
</head>
<body>

<h1>Heading 1</h1>
<p>Some Text...</p>
<br>
<h1>Heading 2</h1>
<p>Some Text...</p>
<br>
<h1>Heading 3</h1>
<h2>Subheading 1</h2>
<p>Some Text...</p>
<br>
<h1>Heading 4</h1>
<h2>Subheading 2</h2>
<p>Some Text...</p>
<h2>Subheading 3</h2>
<p>Some Text...</p>
<br>
<br>
<br>
<pdf:toc />

</body>
</html>
"""

with open("Test.pdf", "w+b") as result_file:
    pisa_status = pisa.CreatePDF(
        html_source,
        dest=result_file,
    )

```

**Comment by akshathakl14** [comment] 2026-02-05 09:59
Hi @fbernhart ,

I tried your code from xhtml2pdf . 
Log file:
[logs.txt](https://github.com/user-attachments/files/25092616/logs.txt)
Code:
[page_test.html](https://github.com/user-attachments/files/25092593/page_test.html)

I tried to upgrade the xhtml2pdf using pip install --upgrade xhtml2pdf.
Requirement already satisfied: 
C:\xxxxx\AppData\Local\yyyy\xhtml2pdf>xhtml2pdf --version
0.2.4

Could you please help me how to solve this issue?

Thanks and regards,
Akshatha

**Comment by fbernhart** [comment] 2026-02-05 23:58
> I tried to upgrade the xhtml2pdf using pip install --upgrade xhtml2pdf.
> Requirement already satisfied: 
> C:\xxxxx\AppData\Local\yyyy\xhtml2pdf>xhtml2pdf --version
> 0.2.4

Please update to a version ≥ 0.2.5, preferably the newest version 0.2.17

**Comment by akshathakl14** [comment] 2026-02-11 05:47
Hi @fbernhart ,

Thank you for helping me resolve this issue.

I was curious about one more thing , is it possible to change the formats of the table representation like below:
Heading 1 ................................ 1
Heading 2 ................................ 2

Now in the above example it will be created as follows:
Heading 1                           1
Heading 2                           2

How can i add the "................................"  in between ? I have tried using this html style but not working 
pdftoc:after {
        content: leader(dotted);
    }

**Comment by fbernhart** [comment] 2026-02-11 07:27
> How can i add the "................................"  in between ?

I don't think that's possible at the moment. See #655

**Comment by akshathakl14** [comment] 2026-02-13 06:47
Hi @fbernhart ,
     Why does <pdf:toc /> always prints at the last page of pdf instead of printing it in start of pdf ?
I was trying it to print in first page but it always writes at last page .

**Comment by fbernhart** [comment] 2026-02-13 06:51
> Hi @fbernhart ,
>      Why does <pdf:toc /> always prints at the last page of pdf instead of printing it in start of pdf ?
> I was trying it to print in first page but it always writes at last page .
>  

Might depend on where you put it in the HTML file. But I haven't used xhtml2pdf in 5 years, so I'm not sure.
