### ISSUE TITLE
Not latin chars?

### ISSUE THREAD

**Issue by isergey** [xhtml2pdf/xhtml2pdf#11] opened 2011-06-29 12:20 UTC
Can't display non latin chars. Document encoding utf-8. How?

**Comment by benjaoming** [comment] 2016-05-01 17:30
This seems to still be an issue.

**Comment by serboctor** [comment] 2016-11-28 15:26
Ok..the last comment was in May. Anyone knows if this is still the case?

**Comment by benjaoming** [comment] 2016-11-28 15:28
It is.

**Comment by jasonmg** [comment] 2017-02-16 05:44
i have this issue too, and tried all the advice above(include related-link issues) not find a good solution yet, any one looking it currently ?

**Comment by serboctor** [comment] 2017-02-16 14:49
@jasonmg I had to download a font that supports all the characters I am using and use this font in the html template before converting to pdf. That is the only approach that worked for me.

**Comment by jasonmg** [comment] 2017-02-17 11:56
@serboctor  thanks very much , it's been solved as you suggested.

**Comment by LegoStormtroopr** [comment] 2017-02-24 04:12
Will check it out soon.

**Comment by shtalinberg** [comment] 2017-03-22 15:16
with   xhtml2pdf==0.2b1

work with russian
```
def render_to_pdf(template_src, context_dict, filename):
    # TODO: for python 3 support check https://spapas.github.io/2015/11/27/pdf-in-django/
    template = get_template(template_src)
    context_dict['STATIC_ROOT'] = settings.STATIC_ROOT
    context_dict['pdf'] = '1'
    context = Context(context_dict)
    html = template.render(context)
    # return HttpResponse(html)
    result = StringIO()
    pdf = pisa.CreatePDF(StringIO(html.encode('utf-8')), result)

    if not pdf.err:
        response = HttpResponse(result.getvalue(), content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename=%s' % filename
        return response
    return HttpResponse('We had some errors! <b>%s</b>' % pdf.err)

```
in template 
`@font-face {font-family: Arial; src: url("{{STATIC_ROOT}}/fonts/arial.ttf"); }`

**Comment by audiolion** [comment] 2017-03-22 17:31
xhtml2pdf only includes certain fonts by default https://xhtml2pdf.readthedocs.io/en/latest/reference.html#fonts

If you want to use other characters you need to include a font that has glyphs for those characters

```
/* Normal */
@font-face {
   font-family: DejaMono;
   src: url(font/DejaVuSansMono.ttf);
}
```

**Comment by sandeepkoduri** [comment] 2017-03-22 17:48
Does this work on Google App Engine, 
We tried different options to use font ttf files from localpath, static path, web path. Nothing worked.
https://github.com/sandeepkoduri/GAE-html-to-pdf/blob/template/pineapple.py 

Debug true doesn't work either.

**Comment by audiolion** [comment] 2017-03-29 14:48
related to #345

**Comment by adrian-chrostowski** [comment] 2018-11-28 19:16
anyone? anything new on the topic?

**Comment by benjaoming** [comment] 2018-11-28 21:17
What do you mean exactly @adrian-chrostowski ?

I think that the comment about using the correct fonts is a kind of fix for most issues: https://github.com/xhtml2pdf/xhtml2pdf/issues/11#issuecomment-288477301

Does that work for you?

**Comment by adrian-chrostowski** [comment] 2018-11-29 09:30
the issue is that the font doesn't load if it's full path is not specified

**Comment by benjaoming** [comment] 2018-11-29 13:33
@adrian-chrostowski okay, that's a different issue then.. so just writing this out of memory... try loading it through HTTP, check your dev server if it is requesting your font when running `runserver` and finally, try adding `file://` and see if that works.

xhtml2pdf is a very stale project, so if you are doing something new, start off with WeasyPrint instead as suggested in the README.

**Comment by luisza** [comment] 2018-11-29 14:55
Could you please create a new issue, and try to explain what do you think is wrong and what could be the correct way.

**Comment by SimonAstani** [comment] 2019-04-10 08:56
@shtalinberg @audiolion  .. Hello does anyone suggest stable solution.. I read all the comments on the issue.. The issue is closed as well. But unable to find the working solution.. 
As the doc suggest. It support certain fonts only.. For others we need to explicitly define font using @font-face  keyword. What we have to load multiple font type at once. Can anyone suggest working examples or reference.

**Comment by DurgaVaidyanathan** [comment] 2020-08-11 13:46
Its been a year...anyone has a stable solution??

**Comment by citizen-stig** [comment] 2020-08-11 19:12
One of possible solutions is [WeasyPrint](https://weasyprint.readthedocs.io/en/latest/)

**Comment by timobrembeck** [comment] 2023-10-07 16:36
Since non-latin chars work for [Arabic / Asian / Hebrew / Persian alphabets](https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support) with specific fonts, I'm going to close this as completed.
If a specific alphabet is still not supported, please open a new issue per character set and font, similar to the existing sub-issues:
- #571
- #587
- #608
- #651

**Closed by timobrembeck** 2023-10-07 16:36 UTC
Labels: fonts
