### ISSUE TITLE
CSS rules not always applied in the same order

### ISSUE THREAD

**Issue by h3** [xhtml2pdf/xhtml2pdf#69] opened 2012-11-02 16:54 UTC
Usually in CSS if you have the following code:

    #content {
        border: 2px solid blue;
    }

    #content {
        border: 2px solid red;
    }

The border of #content should always be red since styles declared last always override previously declared styles.

However this is not the case with xhtml2pdf, with a css declaration like this sometimes the border will be blue, sometimes it will be red.

Since it's an on & off problem, it looks awfully like a threading problem. You can F5 many times and the styles will flips randomly and not necessarily every times. 

I know reportlab isn't thread safe so I was pretty sure it was a threading problem, but it doesn't seems so. I tried with the dev server with --nothreading and with apache+wsgi on a single thread and the problem persist in both cases.

I dumped what the CSS parser was seeing and the CSS code was always right, which leaves us only with one possibility. The CSS rules aren't always applied in the same order.

**Comment by benjaoming** [comment] 2016-05-01 20:12
I would think this is caused by Python 2 ordering by object reference when no other order is specified.

Example:

```
➜  xhtml2pdf git:(fix-71) ✗ python2
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> object()
<object object at 0x7f1724e9b080>
>>> object() > object()
False
>>> object() > object()
False
>>> object() > object()
True
>>> 
```

Creating explicit sorting should fix it.

**Comment by benjaoming** [comment] 2016-05-02 09:48
Closing this for now, but it's in favour of the more universal solution proposed in #299.

**Closed by benjaoming** 2016-05-02 09:48 UTC

**Comment by fbernhart** [comment] 2020-10-04 10:38
Since Python 3.6 dicts are always insertion-ordered; And as we'll be dropping support for Python < 3.6 very soon, this shouldn't be an issue anymore.

I've tested the given example of @h3 and it's always producing the same, correct output on Python 3.8.5.

So maybe we could also close #299?
