### ISSUE TITLE
`NoneType` object has no attribute `splitOn`

### ISSUE THREAD

**Issue by andreyfedoseev** [xhtml2pdf/xhtml2pdf#348] opened 2017-04-10 22:38 UTC
I'm not sure whether is a bug with `xhtml2pdf` or `reportlab`, but since it involves an instance of `PmlTableOfContents` I'm reporting it here.

I have a document that I want to convert to PDF: https://gist.github.com/andreyfedoseev/deaa6dfe0f5b09b594eb99036f7763e4#file-gistfile1-txt

Whenever I do

```python
# `text` is the content of the document referenced above
xhtml2pdf.document.pisaDocument(
    StringIO(text)
)
```

I get the following exception:

```
  File "xhtml2pdf/document.py", line 126, in pisaDocument
    doc.multiBuild(context.story)
  File "reportlab/platypus/doctemplate.py", line 1043, in multiBuild
    self.build(tempStory, **buildKwds)
  File "reportlab/platypus/doctemplate.py", line 956, in build
    self.handle_flowable(flowables)
  File "reportlab/platypus/doctemplate.py", line 829, in handle_flowable
    S = frame.split(f,canv)
  File "reportlab/platypus/frames.py", line 227, in split
    r = flowable.split(self._aW, y-p-s)
  File "reportlab/platypus/tableofcontents.py", line 277, in split
    return self._table.splitOn(self.canv,availWidth, availHeight)
```

If I remove the styles for `h1`, `h2`, and `h3` from the document it runs with no error.

`self` on the last line of the traceback is an instance of `xhtml2pdf.xhtml2pdf_reportlab.PmlTableOfContents`

I'm using `xhtml2pdf==0.0.6` and `reportlab=3.3.0` but I was able to reproduce it with `xhtml2pdf==0.2.b1` as well.

**Comment by stefan6419846** [comment] 2023-10-03 08:29
I cannot reproduce this with `reportlab==3.6.13` when reading the HTML into a string, thus it seems to have been solved in the meantime?

**Comment by timobrembeck** [comment] 2023-10-03 12:23
@stefan6419846 Thanks a lot for investigating this, I'll close the issue for now, let's see if anyone reports it again with detailed info on how to reproduce this.

**Closed by timobrembeck** 2023-10-03 12:23 UTC
