### ISSUE TITLE
link callback and svg

### ISSUE THREAD

**Issue by kssidhu7** [xhtml2pdf/xhtml2pdf#84] opened 2013-03-12 07:43 UTC
I edited the pisaLoader getFileName so that the default suffix is the lower() alphanumeric content-type. That is '.' + subtype of the link, e.g. .png, .svgxml
I was hoping to be able to find where you render images and add a mode for svgxml using this:
http://stackoverflow.com/questions/5835795/generating-pdfs-from-svg-input

But, I am relatively new to python and can't figure out how/ where you handle fetched files/ images.
If you can just tell me where you do this, i will try to make a patch, otherwise please have a look

**Comment by benjaoming** [comment] 2016-05-01 19:15
Duplicate of #73

**Closed by benjaoming** 2016-05-01 19:15 UTC
