### ISSUE TITLE
Error: Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by machineghost** [xhtml2pdf/xhtml2pdf#113] opened 2013-06-12 21:30 UTC
I was able to install xhtml2pdf just fine (inside a virtualenv).  However, it seems something went wrong, because when I try to run the "hello world" from https://github.com/chrisglass/xhtml2pdf/blob/master/doc/usage.rst I get the following error:

> Couldn't get a file descriptor referring to the console

Is there any way to fix this?

**Comment by aidan2129** [comment] 2016-04-19 08:42
+1

**Comment by benjaoming** [comment] 2016-04-19 08:59
Hi @machineghost - are you using the latest prerelease or a stable, and which one?

**Comment by benjaoming** [comment] 2016-04-19 09:00
Eh sorry, I was a bit quick.. didn't see it was a 3 year old issue being bumped. Question goes the same for you, @aidan2129 :)

**Comment by aidan2129** [comment] 2016-04-19 09:11
Haha think i am using the stable but i just did the command `xhtml2pdf [template_name]` without adding `startview -s` and it seemed to work the example in the docs just didnt work for me

**Comment by benjaoming** [comment] 2016-04-19 09:24
You mean `xhtml2pdf test.html --start-viewer` works and `xhtml2pdf test.html` does not? And what's the exact output?

**Comment by aidan2129** [comment] 2016-04-19 09:25
opposite way `xhtml2pdf test.html` works for me

**Comment by aidan2129** [comment] 2016-04-19 09:26
would `xhtml2pdf test.html --start-viewer` not be for a url rather than a template ?

**Comment by benjaoming** [comment] 2016-04-19 09:27
Alright, but what's the output?

**Comment by aidan2129** [comment] 2016-04-19 09:29
Sorry i see the problem i was using a ubuntu virtual box server to generate the template and -s starts the default viewer which the virtual box does not have as i am just ssh into it from windows the output is the same as the title of this issue the problem is that there is no default pdf viewer for me

**Comment by benjaoming** [comment] 2016-04-19 09:43
Alright thanks, closing this, since the issue is confusing and mis-leading then :)

**Closed** 2016-04-19 09:43 UTC
