### ISSUE TITLE
<div> strange behavior

### ISSUE THREAD

**Issue by mengdi** [xhtml2pdf/xhtml2pdf#145] opened 2013-12-04 23:45 UTC
Some of my nested div inside html content don't start a new line, others work correctly. And ul li has very large line spacing. I can't figure out why. I tried the same html content on http://xhtml2pdf.appspot.com/ and all work perfectly.
Could you help me find out why or give me more information about which version does http://xhtml2pdf.appspot.com/ use?
Thanks a lot.

**Comment by timoludwig** [comment] 2023-02-01 21:44
Since this issue is very old, has little info to reproduce and might have been fixed by #635, I'm going to close this now. If somebody experiences similar problems, please provide detailed info how to reproduce it, then we'll reopen the ticket.

**Closed by timoludwig** 2023-02-01 21:44 UTC
