### ISSUE TITLE
Problem rendering tables with chrome, works with firefox

### ISSUE THREAD

**Issue by flo7842** [xhtml2pdf/xhtml2pdf#553] opened 2021-05-14 14:59 UTC
Hello everyone, I have a problem with rendering tables with google chrome, I get a black line while with firefox it works perfectly

**Comment by timoludwig** [comment] 2021-05-22 11:54
What do you mean exactly? The PDF generating process happens server-side, so it should not matter which browser you're using. Or do you mean the resulting PDF looks different when opened in both browsers? If so, then that would be an issue of the browser's PDF viewer... Can you maybe elaborate your problem and attach the PDF file you're referring to?

**Comment by timoludwig** [comment] 2023-02-01 22:19
Closing since the issue author did not respond.
If you still experience the problem, please let us know how to reproduce it.

**Closed by timoludwig** 2023-02-01 22:19 UTC
Labels: needs-reproduction-info, tables
