### ISSUE TITLE
make rtl languages from left

### ISSUE THREAD

**Issue by efazati** [xhtml2pdf/xhtml2pdf#72] opened 2013-01-11 18:45 UTC
for example Persian text must start from right but your result seems like this
Farsi / Persian: .‫یم نم‬
‫مروخب هشيش درد ساسحا ِنودب مناوت‬
also in PDF separate character

correct Persian من می نوانم ...

ps: maybe i couldn't say the problem. for example correct word is "word" but your result is "dorw"

**Comment by nabil25x** [comment] 2020-10-14 19:25
did you find the solution?

**Comment by fbernhart** [comment] 2020-10-14 20:17
@nabil25x It has been implemented recently.

Check out the newest version 0.2.5.

Right-to-left should work for Arabic, Persian, Hebrew, Pashto, etc.

Make sure to also read the section in the docs about it.
 https://xhtml2pdf.readthedocs.io/en/latest/reference.html#arabic-hebrew-persian-etc-fonts-support

**Comment by nabil25x** [comment] 2020-10-14 20:41
@fbernhart 
Thank you, I've seen the docs, but it didn't work with me. I asked on stackoverflow and showed my code, if you may take a look : 
https://stackoverflow.com/questions/64360105/how-to-export-arabic-characters-to-pdf-in-xhtml2pdf
Hope u can help :(

**Comment by fbernhart** [comment] 2020-10-14 21:09
I don't have a PC available right now to test anything, but from just looking at your StackOverflow question:

It's not working, because you haven't used the custom font-family anywhere. You only defined it.

Make sure you add `p { font-family: Amiri }` to your style section.

Probably we should add some more examples to the documentation there.

Two more things:
- You only have to use `<pdf:language ...>` once. There's no need to apply it twice.

- There is also a closing `</div>` tag missing.

But your main problem arises from the first point.

**Comment by nabil25x** [comment] 2020-10-14 21:18
Thank you for taking a look.
All the errors you informed, I solved them.
But the problem is still unsolved, I even used the font you used in the docs, still nothing..
1 - is it okay to use UTF-8?? 
2 - <pdf:language...> does it have to be in specific class? 

Here's my PDF : 
![image](https://user-images.githubusercontent.com/48418186/96046242-d7401700-0e7b-11eb-921d-87b9398154e2.png)

Don't worry about the english stuff. The english squares are the arabic characters appearently.

**Comment by nabil25x** [comment] 2020-10-14 21:19
my HTML : 
```
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <head>
    
    <title>{{title}}</title>
    <style type="text/css">
        

        .header {
            font-size: 20px;
            font-weight: 100;
            text-align: center;
            color: #007cae;
        }

        .title {
            font-size: 22px;
            font-weight: 100;
            /* text-align: right;*/
            padding: 10px 20px 0px 20px;
        }

        .title span {
            color: #007cae;
        }

        .details {
            padding: 10px 20px 0px 20px;
            text-align: left !important;
            /*margin-left: 40%;*/
        }

        .hrItem {
            border: none;
            height: 1px;
            /* Set the hr color */
            color: #333;
            /* old IE */
            background-color: #fff;
            /* Modern Browsers */
        }
        @font-face {font-family: RTLFont; src: url('{% static "MarkaziText-Regular.ttf"%}')}
         p { font-family: RTLFont }
        body {
            font-weight: 200;
            font-size: 14px;
            font-family: RTLFont;
        }
    </style>
</head>

<body>
    <div class='wrapper'>
        <div class='header'>
            <p class='title'>Invoice # {{ invoice_ID }} </p>
        </div>
        <div>
            <div class='details'>
                <pdf:language name="arabic"/>
                
                <p>شسيشسي</p>            
                customername : {{customer_name}} <br><hr>
                customer number : {{customer_num}}<br><hr>
                Date : {{date}}<br><hr>
                {{table}}<br><hr>
                {{2columnsTable}}<br><hr>
                {{notes}}<br><hr>
                {{theUser}}<br>
                <hr class='hrItem' />
            </div>
        </div>
    </div>
</body>

</html>
```

**Comment by fbernhart** [comment] 2020-10-14 21:45
@nabil25x 

The position of the <pdf:language ...> tag shouldn't matter. It should be recognised anywhere.

I'm not am expert ... but do you even have to use encoding? I guess just using the variable `html` should also do the job.

Maybe your problem is here:
Are you sure, that your django setup is correct? I haven't worked with django before, so I can't really tell.
Just make sure, that you're really able to load the .ttf font. That the path is correct etc.

Can you try it locally? Download the font and set the url to `url('C:\\myfolder\\myfont')`, or something similar, depending on your OS.

If the pdf will then render correctly, there is a problem with your django setup and not with xhtml2pdf.

**Comment by nabil25x** [comment] 2020-10-14 22:11
@fbernhart 
Man... you're my hero
Thank you lol, It Worked!

**Comment by fbernhart** [comment] 2020-10-14 22:17
@nabil25x 

Now I'm curious! 😁 What was the problem in the end? A wrong path to the .ttf file?

I'm glad that you got it running.

**Comment by nabil25x** [comment] 2020-10-14 22:19
Yep, it was the path. Thank you 4th time

**Closed** 2020-10-15 13:35 UTC
