### ISSUE TITLE
Add support for `word-wrap` CSS property

### ISSUE THREAD

**Issue by alispa** [xhtml2pdf/xhtml2pdf#601] opened 2022-03-13 17:16 UTC
It would be very handy to have support for the CSS ` word-wrap` property. Especially for `word-wrap: break-word;` which would tables and cells make much more reliable.

**Comment by rads92stx** [comment] 2022-08-26 11:50
Agree on that!

**Comment by timoludwig** [comment] 2023-02-02 13:58
Duplicate of #379 and #339

**Closed by timoludwig** 2023-02-02 13:58 UTC
Labels: feature request, CSS

**Comment by sneharane588** [comment] 2024-05-15 11:52
word-wrap property is not supported.
However, " -pdf-word-wrap: CJK;" only works for few of the HTML data samples for me.
