### ISSUE TITLE
Static Frame for the footer doesn't work properly

### ISSUE THREAD

**Issue by barrabaja** [xhtml2pdf/xhtml2pdf#613] opened 2022-05-13 14:18 UTC
Since version 0.2.7 the static frame for the footer has stopped working correctly, e.g. in the documentation examples.

**Comment by timoludwig** [comment] 2023-02-02 14:15
Is this a duplicate of #653, #644 and #564?
@barrabaja can you check whether this problem is fixed in the latest release?

**Comment by vishalpathak24** [comment] 2023-02-05 09:17
Its not working for me

```    
@page {
        size: a4 portrait;
        @frame header_frame {           /* Static frame */
            -pdf-frame-content: header_content;
            left: 50pt; width: 512pt; top: 0pt; height: 40pt;
        }
        @frame content_frame {             /* Content frame */
            left: 50pt; width: 512pt; top: 40pt; height: 632pt;
        }
        @frame footer_frame {           /* Static frame */
            -pdf-frame-content: footer_content;
            -pdf-frame-border: 1;
            left: 50pt; width: 512pt; top: 772pt; height: 20pt;
        }
    }
```
```
<body>
<div id="header_frame">
        I am header
</div>
<div id="footer_frame">
    I am footer
</div>
</body>
```
Generates text "I am footer" on top but footer box in bottom.

**Comment by barrabaja** [comment] 2023-02-16 21:43
> Is this a duplicate of #653, #644 and #564?
> @barrabaja can you check whether this problem is fixed in the latest release?

Sure! I can confirm that the problem of version 0.2.7 with the footer is solved

version: xhtml2pdf == 0.2.9

**Closed** 2024-02-29 18:33 UTC
Labels: needs reproduction info, question
