### ISSUE TITLE
Cannot import name 'getStringIO' from 'reportlab.lib.utils' 

### ISSUE THREAD

**Issue by hellsing23** [xhtml2pdf/xhtml2pdf#589] opened 2022-02-18 14:04 UTC
Who have same problem?

error code:
  File "/code/apps/shipments/functions.py", line 37, in <module>
    from xhtml2pdf import pisa
  File "/usr/local/lib/python3.9/site-packages/xhtml2pdf/pisa.py", line 19, in <module>
    from xhtml2pdf.document import pisaDocument
  File "/usr/local/lib/python3.9/site-packages/xhtml2pdf/document.py", line 4, in <module>
    from xhtml2pdf.context import pisaContext
  File "/usr/local/lib/python3.9/site-packages/xhtml2pdf/context.py", line 11, in <module>
    import xhtml2pdf.parser
  File "/usr/local/lib/python3.9/site-packages/xhtml2pdf/parser.py", line 32, in <module>
    from xhtml2pdf.tables import *  # TODO: Kill wild import!
  File "/usr/local/lib/python3.9/site-packages/xhtml2pdf/tables.py", line 8, in <module>
    from xhtml2pdf.tags import pisaTag
  File "/usr/local/lib/python3.9/site-packages/xhtml2pdf/tags.py", line 10, in <module>
    from xhtml2pdf import xhtml2pdf_reportlab
  File "/usr/local/lib/python3.9/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 20, in <module>
    from reportlab.lib.utils import flatten, open_for_read, getStringIO, \
ImportError: cannot import name 'getStringIO' from 'reportlab.lib.utils' (/usr/local/lib/python3.9/site-packages/reportlab/lib/utils.py)

**Comment by anze3db** [comment] 2022-02-18 15:22
We noticed the same issue. Looks like the problem was caused by reportlab version 3.6.7. A workaround for this is to pin reportlab to 3.6.6.

**Comment by anushbmx** [comment] 2022-02-18 15:56
Quick fix  is to add `reportlab==3.6.6` in requirements.txt until this commit is merged.

**Comment by pmourelle** [comment] 2022-02-18 20:37
Big issue on this is having reportlab version open instead of pinning an specific version here:
https://github.com/xhtml2pdf/xhtml2pdf/blob/master/requirements.txt#L7

**Closed** 2022-02-21 14:07 UTC
