### ISSUE TITLE
`LayoutError: Flowable too large` when embedding large images

### ISSUE THREAD

**Issue by dberardo-com** [xhtml2pdf/xhtml2pdf#630] opened 2022-09-29 18:18 UTC
Hello there,

i am trying to use this library to produce pdfs with images inside. Those are just regular images, quite big in size (800x1000 perhaps). I have tried first to embed those images as svgs in the report, but i get a parsing error from the library, so then i decided to switch to "png" or "jpg" import.

I manage to import some images, but when i add others, i get this error:

LayoutError: Flowable <PmlParagraph at 0x7f6f6b3b6af0 frame=body>(841.8897637795277 x 2953.6174999999994) too large on page 2 in frame 'body'(841.8897637795277 x 595.2755905511812*) of template 'body'

the only way to fix this is to assign a width attribute to the body element to quite huge values, but the pdf at the end gets unreadable.

i have no idea whether the vendor css attributes are actually having any effect at the moment, i have tried many combinations, like: `-pdf-keep-in-frame-mode: truncate; ` etc..

could you please provide help?

**Comment by timoludwig** [comment] 2023-02-01 22:01
Duplicate of #68

**Closed by timoludwig** 2023-02-01 22:01 UTC
Labels: duplicate
