### ISSUE TITLE
Add support for `word-wrap` CSS property

### ISSUE THREAD

**Issue by kostyachum** [xhtml2pdf/xhtml2pdf#379] opened 2017-12-12 07:52 UTC
I have some Chinese text to render to HTML and it appears there are big issues with it and problem it not only about Chinese, but any text without white spaces - ` word-wrap` have no effect at all. Can somebody suggest how to solve the issue?

![peph 517274 isabella_testfggggggg_gssggfffff in house curator marketing top20 pdf 1](https://user-images.githubusercontent.com/5758428/33873033-2242d63e-df22-11e7-9f22-33f625113ec1.png)

**Comment by jtesch** [comment] 2018-05-22 21:56
According to the [docs](http://xhtml2pdf.readthedocs.io/en/latest/reference.html), word wrap isn't supported. 

Do wish this was supported though!

**Comment by cringham** [comment] 2021-09-01 16:41
For those who land here looking for an alternative solution, @p-mazhnik identified an equivalent in [this comment](https://github.com/xhtml2pdf/xhtml2pdf/issues/339#issuecomment-540196694) which works for me:

> @vuonghv try to use property
> 
> ```
>     -pdf-word-wrap: CJK;
> ```
> 
> It helped me. I could find this only in the source code, there is no documentation for this for some reason.
> Notice that word may be broken at any character, as in `word-break: break-all;`

**Comment by timoludwig** [comment] 2023-02-02 13:57
Duplicate of #339

**Closed by timoludwig** 2023-02-02 13:57 UTC

**Comment by sneharane588** [comment] 2024-05-15 11:01
word-wrap property is not supported.
However, " -pdf-word-wrap: CJK;" only works for few of the HTML data samples for me.
