### ISSUE TITLE
Table layout broken

### ISSUE THREAD

**Issue by honghh2018** [xhtml2pdf/xhtml2pdf#557] opened 2021-06-08 12:20 UTC
Hi All,
    I am going to  convert my index.html to .pdf, but the table like below abnormal from the index.html.

![image](https://user-images.githubusercontent.com/41668708/121183390-99728180-c896-11eb-9712-a576877c4c98.png)
    The html table like below was the normal
     
![image](https://user-images.githubusercontent.com/41668708/121183546-c888f300-c896-11eb-9b14-0c58a85fe9ac.png)

How can i fix this issue ?
Any advices would be apprecicated.
Best,
hanhuihong

**Comment by skwars7** [comment] 2021-06-25 16:44
can you share the HTML file as well which you are using?

**Comment by timoludwig** [comment] 2023-02-02 14:21
Since the author did not provide more information, I'm going to close this.
If you still experience this problem, please let us know how to reproduce it.

**Closed by timoludwig** 2023-02-02 14:21 UTC
Labels: needs reproduction info, tables, bug
