### ISSUE TITLE
It's not work thai language.

### ISSUE THREAD

**Issue by ninenox** [xhtml2pdf/xhtml2pdf#235] opened 2015-06-09 13:08 UTC
![pdf](https://cloud.githubusercontent.com/assets/12573570/8058356/18d24f4c-0ee3-11e5-8dc8-33b1af0bbbdf.png)

Please help me. This is my code. 
=============================================
    

def generate_PDF(request):
    data = {}

    template = get_template('test.html')
    html  = template.render(Context(data))

    file = open('test.pdf', "w+b")
    pisaStatus = pisa.CreatePDF(html.encode('utf-8'), dest=file,encoding='utf-8')

    file.seek(0)
    pdf = file.read()
    file.close()
    return HttpResponse(pdf, content_type='application/pdf')

**Comment by ninenox** [comment] 2015-06-10 09:17
<style type='text/css'>
        @font-face {font-family: thaisanlite;
            src: url(D:/thaisanslite_r1.ttf);
        }
    </style>
I can show thai language but why src is fix path, It's can't use absolute path.

**Comment by benjaoming** [comment] 2016-05-01 17:44
This is a duplicate of #11

The issue with font paths may very well be solved so please try that again with current `develop` branch or latest alpha `pip install --pre xhtml2pdf`

**Closed by benjaoming** 2016-05-01 17:44 UTC
