### ISSUE TITLE
Cannot Add Images as a Link

### ISSUE THREAD

**Issue by siddydutta** [xhtml2pdf/xhtml2pdf#759] opened 2024-04-15 14:02 UTC
### Describe the Bug
Wrapping an `<img>` with the `<a>` tag seems to have no effect. Hence, cannot add images as links.

### Minimal Example to Reproduce
```python3
from xhtml2pdf import pisa

source_html = """<html>
<body>
<a href="http://www.stackoverflow.com">
    <img src="https://dummyimage.com/1038x450/000/0011ff&text=sample+image"/>
</a>
</body>
</html>"""
output_filename = "output.pdf"
result_file = open(output_filename, "w+b")
pisa.CreatePDF(
    source_html,
    dest=result_file)
result_file.close()
```

### Expected Behavior
The image should be a hyperlink.

### Actual Behavior
The image is not a hyperlink.

### Additional Information
There is a hacky solution: https://stackoverflow.com/questions/32833922/unable-to-create-an-image-hyperlink-with-xhtml2pdf/35300776#35300776 for this, but it does not work with a larger image size.

### System Information
OS version: macOS Sonoma 14.4.1
Python version: 3.8
XHTML2PDF version: 0.2.15

**Comment by Tanuj-Shriyan** [comment] 2024-06-20 16:48
Have we found a work around for this? The stackoverflow question op mentioned them using another library.

**Comment by timobrembeck** [comment] 2024-07-20 20:10
@siddydutta thanks for reporting the issue, but please make sure to use the search before opening a new ticket. This problem was reported before, so this is a duplicate of #491.

@Tanuj-Shriyan no, I don't know a workaround for this. Also, there is no active community maintaining this project, so if you want to have this problem fixed, the best approach is to look into the code yourself :sweat_smile: 
I'd be happy to review any contributions if you can resolve the issue.

**Closed by timobrembeck** 2024-07-20 20:10 UTC
Labels: bug

**Comment by Tanuj-Shriyan** [comment] 2024-07-22 16:40
@timobrembeck Links just started working using the library. I just used the anchor tag element! :)
