### ISSUE TITLE
Not working with non-latin chars

### ISSUE THREAD

**Issue by emirotin** [xhtml2pdf/xhtml2pdf#15] opened 2011-07-18 14:02 UTC
Please download http://dl.dropbox.com/u/137209/pisa_problem.zip
The test.html is a trivial UTF-8 encoded valid XHTML Strict
The test.pdf is the result of 

    pisa --encoding utf-8 test.html

(the same happens when not speccifying the encoding)

2 screenshots show the source opened in the text editor, and the result opened in Preview

**Comment by benjaoming** [comment] 2016-05-01 17:40
Duplicate of #11

**Closed by benjaoming** 2016-05-01 17:40 UTC
