### ISSUE TITLE
`TTFError: Can't open file` on Windows

### ISSUE THREAD

**Issue by thatisfree** [xhtml2pdf/xhtml2pdf#607] opened 2022-04-11 22:30 UTC
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">TTFError at /quotation/pdf</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Can't open file "C:\Users\User\AppData\Local\Temp\tmplpih5nyn.ttf"</pre>

Request Method: | GET
-- | --
http://localhost:8080/quotation/pdf
4.0.3
TTFError
Can't open file "C:\Users\User\AppData\Local\Temp\tmplpih5nyn.ttf"
C:\Users\User\PycharmProjects\control\venv\lib\site-packages\reportlab\pdfbase\ttfonts.py, line 161, in TTFOpenFile
C:\Users\User\PycharmProjects\control\venv\Scripts\python.exe
3.10.1
['C:\\Users\\User\\PycharmProjects\\control\\cnc_app',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib',  'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310',  'C:\\Users\\User\\PycharmProjects\\control\\venv',  'C:\\Users\\User\\PycharmProjects\\control\\venv\\lib\\site-packages']

</body>
</html>

**Comment by ivvitikhonov** [comment] 2023-01-04 14:34
These answers saved my time - https://github.com/xhtml2pdf/xhtml2pdf/issues/623

**Comment by timoludwig** [comment] 2023-02-01 21:33
Since #623 seems to be a duplicate of this issue but provides more info, I'm going to close this one.

**Closed by timoludwig** 2023-02-01 21:33 UTC
Labels: bug, platform-specific
