### ISSUE TITLE
Add support for `:not()` CSS selector

### ISSUE THREAD

**Issue by Dexus** [xhtml2pdf/xhtml2pdf#578] opened 2021-12-06 17:41 UTC
xhtml2pdf.w3c.cssParser.CSSParseError: Selector Pseudo Function closing ')' not found:: (':not( ', ':local-link )):after')

```CSS

a:not( :local-link ):after {
    content: " <" attr(href) "> ";
}
```

**Comment by alien8ion** [comment] 2022-12-16 07:07
I'm experiencing a similar issue with version 0.2.8 when I link to bootstrap 4.1.3 with the following:

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
```

with this single line in the <head></head> of the HTML document, I get the following error:

```
Selector Pseudo Function closing ')' not found:: (':not(', '[href]):not([tabinde')
```

If I comment out the line, the error goes away.

**Comment by timoludwig** [comment] 2023-02-02 17:51
Duplicate of #363

**Closed by timoludwig** 2023-02-02 17:51 UTC
Labels: feature request, CSS
