### ISSUE TITLE
Nesting tags in a list prevents numbering

### ISSUE THREAD

**Issue by enrique-rodriguez** [xhtml2pdf/xhtml2pdf#727] opened 2023-10-17 11:35 UTC
> This is most likely a duplicate of #611 and should have been fixed by #635.

This is still an issue. Please see the following example to reproduce

```
from xhtml2pdf import pisa


contents = """

<ol>
    <li>Section 1
        <ol>
            <li>Item 1
                <ol>
                    <li>Sub Item 1</li>
                    <li>Sub Item 2</li>
                </ol>
            </li>
            <li>Item 2</li>
        </ol>
    </li>
    <li>Section <span style="color: red">2</span>
        <ol>
            <li>Item 1
                <ol>
                    <li>Sub Item 1</li>
                    <li>Sub Item 2</li>
                </ol>
            </li>
            <li>Item 2</li>
        </ol>
    </li>

</ol>

"""


with open("bug.pdf", "w+b") as fd:
    pisa.CreatePDF(contents, fd)
```

Notice that the Section 2 numberling is missing.

_Originally posted by @enrique-rodriguez in https://github.com/xhtml2pdf/xhtml2pdf/issues/550#issuecomment-1766226148_

**Comment by timobrembeck** [comment] 2023-10-17 11:46
Duplicate of #550

**Closed by timobrembeck** 2023-10-17 11:46 UTC
